### PR TITLE
Add password authentication

### PR DESCRIPTION
**Pull request by elisaado**

### CODE REVIEW

**Comment by lieuwex** [comment]
Thanks for the PR, is there a good use case for this? I'm afraid to encourage people to write software that stores the users' passwords in the database for no reason.

**Comment by elisaado** [comment]
I figured that, because (in the case of zermelo) the token can't be revoked, but a password can be changed, it would be safer for my own app. (I am developing a product similar to simplyHomework)

**Comment by lieuwex** [comment]
If I'm not mistaken, [the docs](https://confluence.zermelo.nl/display/DEV/API+Authentication) seem to suggest that we get an `expires_in`. Which seems to suggest the access token is short lived. After I search, I found that the library [already exposes](https://github.com/simplyGits/zermelo/blob/75f73588f409d1ebd8b262c7afc8df59e0dda615/src/sessionInfo.js#L16) this date. Which the user of this library can simply check to relogin (or set a timer, or whatever).

The [same docs](https://confluence.zermelo.nl/display/DEV/API+Authentication) also has a big warning on top "Note that you are **not allowed** to ask a user for their username/password!", which seems pretty convincing.

If you _really_ want to use password auth, which I strongly recommend **against**, you can expose this function in a separate library. You can just create a `SessionInfo` and provide that to the `Zermelo` constructor.

**Comment by elisaado** [comment]
Good point, I guess I'll use use the method you described and just store the tokens.

Thanks for considering my pull request even after having graduated like 2 years ago.

**Pull request closed without merging**
